In [ ]:
import torch
import torch.nn as nn

In [ ]:
x = torch.randn(2, 3)
x,torch.transpose(x, 0, 1)

(tensor([[-0.3097,  1.4207, -1.0598],
         [ 0.2545,  0.3161,  0.1999]]),
 tensor([[-0.3097,  0.2545],
         [ 1.4207,  0.3161],
         [-1.0598,  0.1999]]))

In [ ]:
x = torch.randn(2, 3,4)

x,torch.transpose(x, 0, 1)

(tensor([[[-0.0057,  0.4720,  0.9030,  0.2891],
          [ 3.0144,  2.5445,  0.0621,  1.4230],
          [-0.7559,  1.0859, -0.7060, -0.2135]],
 
         [[-0.5132,  0.5103, -0.9168,  0.1837],
          [ 1.9739, -0.6299, -1.3949, -1.2555],
          [-1.5860, -0.4323,  0.0674,  1.0376]]]),
 tensor([[[-0.0057,  0.4720,  0.9030,  0.2891],
          [-0.5132,  0.5103, -0.9168,  0.1837]],
 
         [[ 3.0144,  2.5445,  0.0621,  1.4230],
          [ 1.9739, -0.6299, -1.3949, -1.2555]],
 
         [[-0.7559,  1.0859, -0.7060, -0.2135],
          [-1.5860, -0.4323,  0.0674,  1.0376]]]))